In [ ]:
import numpy as np
import pandas as pd

In [2]:
transactions = pd.read_csv('transactions.csv', sep=';')
transactions

,date,entreprise,ticker,secteur,type_operation,quantite,prix_unitaire,frais,portefeuille
0,2026-09-14,Heliona,HEL,Santé,Achat,12,59.28,1.50,Portefeuille C
1,2023-07-10,Bexia,BEX,Finance,Achat,208,99.93,22.23,Portefeuille B
2,2023-06-01,Ionet,ION,Technologie,Achat,202,65.37,12.98,Portefeuille B
3,2023-05-19,Moravia,MOR,Finance,Vente,10,100.86,1.50,Portefeuille A
4,2024-04-05,Novatek,NOV,Industrie,Achat,263,65.67,13.21,Portefeuille B
...,...,...,...,...,...,...,...,...,...
2995,2023-11-28,Ecovia,ECO,Énergie,Vente,50,56.91,2.94,Portefeuille C
2996,2025-08-05,Heliona,HEL,Santé,Achat,175,63.21,12.67,Portefeuille A
2997,2026-05-29,Novatek,NOV,Industrie,Achat,66,63.86,4.92,Portefeuille A
2998,2026-07-15,Bexia,BEX,Finance,Vente,275,194.12,46.51,Portefeuille B
2999,2023-09-20,Alphex,ALP,Technologie,Vente,215,46.23,10.16,Portefeuille C

Affichez le nombre de lignes et de colonnes du DataFrame `transactions`    
Affichez les types de chaque colonne avec `.info()`      
Affichez les statistiques descriptives des colonnes numériques avec `.describe()`

In [3]:
transactions.shape

(3000, 9)

In [4]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            3000 non-null   str
 1   entreprise      3000 non-null   str
 2   ticker          3000 non-null   str
 3   secteur         3000 non-null   str
 4   type_operation  3000 non-null   str
 5   quantite        3000 non-null   int64
 6   prix_unitaire   2980 non-null   float64
 7   frais           3000 non-null   float64
 8   portefeuille    3000 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 211.1 KB

In [5]:
transactions.describe()

          quantite  prix_unitaire        frais
count  3000.000000    2980.000000  3000.000000
mean    153.920000      74.004101     9.354520
std      85.410811      34.241613     8.100171
min       5.000000      28.260000     1.500000
25%      79.000000      49.055000     3.490000
50%     157.000000      65.190000     7.175000
75%     227.000000      86.130000    12.372500
max     300.000000     206.530000    64.190000

1. Combien de valeurs manquantes contient la colonne `prix_unitaire` ?       
2. Affichez les lignes correspondantes (celles où `prix_unitaire` est manquant)  

3. Remplacez les valeurs manquantes de `prix_unitaire` par le prix moyen **du même ticker** (et non la moyenne globale, qui serait moins pertinente pui\sque chaque titre a un prix très différent). Indice : `transactions['prix_unitaire'] = transactions.groupby('ticker')['prix_unitaire'].transform(lambda x: x.fillna(x.mean()))`.

In [6]:
transactions['prix_unitaire'].isna().sum()

np.int64(20)

In [8]:
transactions[transactions['prix_unitaire'].isna()].head(5)

,date,entreprise,ticker,secteur,type_operation,quantite,prix_unitaire,frais,portefeuille
187,2025-05-21,Koralis,KOR,Immobilier,Achat,258,NaN,7.63,Portefeuille A
214,2026-02-03,Gamora,GAM,Technologie,Achat,91,NaN,11.22,Portefeuille A
235,2025-02-12,Dynatek,DYN,Industrie,Achat,269,NaN,8.49,Portefeuille B
236,2025-05-26,Moravia,MOR,Finance,Achat,278,NaN,32.97,Portefeuille A
622,2024-04-25,Orialis,ORA,Énergie,Vente,254,NaN,11.03,Portefeuille B

In [15]:
# Remplacez les valeurs manquantes de `prix_unitaire` par le prix moyen **du même ticker**

transactions['prix_unitaire'] = transactions.groupby('ticker')['prix_unitaire'].transform(lambda x : x.fillna(x.mean()))

In [16]:
transactions['prix_unitaire'].isna().sum()

np.int64(0)

1.  Créez une colonne `montant_brut` = `quantite` × `prix_unitaire` ;
2. Créez une colonne `montant_net` qui vaut `montant_brut + frais` pour un `'Achat'` (les frais s'ajoutent à ce qu'on paie), et `montant_brut - frais` pour une `'Vente'` (les frais se déduisent de ce qu'on reçoit). Indice : utilisez `np.where(transactions['type_operation'] == 'Achat', ..., ...)`.

In [18]:
transactions['montant_brut'] = transactions['quantite'] * transactions['prix_unitaire']
transactions['montant_net'] = np.where(
    transactions['type_operation']=='Achat',
    transactions['montant_brut'] + transactions['frais'],
    transactions['montant_brut'] - transactions['frais']

)

transaction_new = transactions[['montant_brut', 'montant_net']]
display(transactions.head(5))

,date,entreprise,ticker,secteur,type_operation,quantite,prix_unitaire,frais,portefeuille,montant_brut,montant_net
0,2026-09-14,Heliona,HEL,Santé,Achat,12,59.28,1.50,Portefeuille C,711.36,712.86
1,2023-07-10,Bexia,BEX,Finance,Achat,208,99.93,22.23,Portefeuille B,20785.44,20807.67
2,2023-06-01,Ionet,ION,Technologie,Achat,202,65.37,12.98,Portefeuille B,13204.74,13217.72
3,2023-05-19,Moravia,MOR,Finance,Vente,10,100.86,1.50,Portefeuille A,1008.60,1007.10
4,2024-04-05,Novatek,NOV,Industrie,Achat,263,65.67,13.21,Portefeuille B,17271.21,17284.42

1. Affichez toutes les opérations du secteur `'Technologie'` 

2. Affichez toutes les ventes (`type_operation == 'Vente'`) dont le `montant_brut` dépasse 20 000 

3. Combien y a-t-il d'opérations concernant le `'Portefeuille B'` dans le secteur `'Énergie'` ?

In [ ]:
# 1. Affichez toutes les opérations du secteur `'Technologie'` 

technologie = transactions[transactions['secteur'] == 'Technologie']
print(f"{len(technologie)} opérations dans le secteur Technologie")
display(technologie.head())

607 opérations dans le secteur Technologie

,date,entreprise,ticker,secteur,type_operation,quantite,prix_unitaire,frais,portefeuille,montant_brut,montant_net
2,2023-06-01,Ionet,ION,Technologie,Achat,202,65.37,12.98,Portefeuille B,13204.74,13217.72
5,2023-10-23,Gamora,GAM,Technologie,Achat,227,113.66,22.53,Portefeuille B,25800.82,25823.35
6,2023-10-13,Alphex,ALP,Technologie,Vente,162,49.24,8.49,Portefeuille B,7976.88,7968.39
7,2025-11-24,Ionet,ION,Technologie,Achat,104,70.66,4.56,Portefeuille A,7348.64,7353.20
10,2023-03-17,Alphex,ALP,Technologie,Achat,128,55.95,5.29,Portefeuille A,7161.60,7166.89

In [ ]:
# 2. Affichez toutes les ventes (`type_operation == 'Vente'`) dont le `montant_brut` dépasse 20 000 

grosses_ventes = transactions[(transactions['type_operation'] == 'Vente') & (transactions['montant_brut'] > 20000)]
print(f"{len(grosses_ventes)} ventes dépassent 20 000")
display(grosses_ventes.head())

168 ventes dépassent 20 000

,date,entreprise,ticker,secteur,type_operation,quantite,prix_unitaire,frais,portefeuille,montant_brut,montant_net
18,2023-01-26,Moravia,MOR,Finance,Vente,241,101.96,17.80,Portefeuille A,24572.36,24554.56
25,2026-04-16,Ionet,ION,Technologie,Vente,277,87.79,20.87,Portefeuille C,24317.83,24296.96
86,2024-11-25,Dynatek,DYN,Industrie,Vente,251,80.69,13.43,Portefeuille A,20253.19,20239.76
154,2024-05-20,Ionet,ION,Technologie,Vente,250,81.00,10.15,Portefeuille A,20250.00,20239.85
173,2025-01-23,Gamora,GAM,Technologie,Vente,248,133.98,37.94,Portefeuille C,33227.04,33189.10

In [32]:
nb_b_energie =len(transactions[(transactions['portefeuille'] == 'Portefeuille B') & (transactions['secteur'] == 'Énergie')])

print(f"Nombre d'opérations du Portefeuille B dans le secteur Énergie : {nb_b_energie}")

Nombre d'opérations du Portefeuille B dans le secteur Énergie : 154

1.  Affichez les 10 opérations avec le `montant_brut` le plus élevé ;
2. Affichez les opérations triées par `date` croissante, pour le `ticker` `'NOV'` uniquement.

In [33]:
print('Les 10 Transactions avec le montant_brut le plus élévé')
display(transactions.sort_values(by='montant_brut', ascending=False).head(10))

Les 10 Transactions avec le montant_brut le plus élévé

,date,entreprise,ticker,secteur,type_operation,quantite,prix_unitaire,frais,portefeuille,montant_brut,montant_net
1837,2026-08-17,Gamora,GAM,Technologie,Vente,285,202.24,48.33,Portefeuille B,57638.40,57590.07
78,2026-06-15,Gamora,GAM,Technologie,Achat,296,189.87,64.19,Portefeuille B,56201.52,56265.71
519,2026-06-09,Gamora,GAM,Technologie,Vente,294,182.81,54.95,Portefeuille B,53746.14,53691.19
2998,2026-07-15,Bexia,BEX,Finance,Vente,275,194.12,46.51,Portefeuille B,53383.00,53336.49
1445,2026-09-07,Bexia,BEX,Finance,Vente,291,180.62,40.48,Portefeuille B,52560.42,52519.94
1320,2025-12-05,Gamora,GAM,Technologie,Vente,300,173.57,28.33,Portefeuille A,52071.00,52042.67
850,2026-09-03,Bexia,BEX,Finance,Achat,280,184.73,60.47,Portefeuille C,51724.40,51784.87
614,2026-08-11,Bexia,BEX,Finance,Achat,272,189.65,36.21,Portefeuille B,51584.80,51621.01
2076,2026-01-23,Gamora,GAM,Technologie,Vente,289,176.63,45.94,Portefeuille C,51046.07,51000.13
230,2026-08-31,Bexia,BEX,Finance,Vente,272,183.09,51.61,Portefeuille B,49800.48,49748.87

In [ ]:
# 2. Affichez les opérations triées par `date` croissante, pour le `ticker` `'NOV'` uniquement.

transactions[transactions['ticker'] == 'NOV'].sort_values('date', ascending=True).head(10)

,date,entreprise,ticker,secteur,type_operation,quantite,prix_unitaire,frais,portefeuille,montant_brut,montant_net
2416,2023-01-03,Novatek,NOV,Industrie,Achat,277,74.40,23.02,Portefeuille B,20608.80,20631.82
2364,2023-01-06,Novatek,NOV,Industrie,Achat,58,72.93,2.80,Portefeuille B,4229.94,4232.74
2527,2023-01-17,Novatek,NOV,Industrie,Achat,242,72.61,13.17,Portefeuille A,17571.62,17584.79
145,2023-02-10,Novatek,NOV,Industrie,Achat,116,71.90,7.41,Portefeuille A,8340.40,8347.81
384,2023-02-17,Novatek,NOV,Industrie,Vente,162,70.26,12.28,Portefeuille B,11382.12,11369.84
1528,2023-03-07,Novatek,NOV,Industrie,Vente,285,70.95,10.80,Portefeuille C,20220.75,20209.95
2366,2023-03-08,Novatek,NOV,Industrie,Vente,240,70.11,8.57,Portefeuille B,16826.40,16817.83
1430,2023-03-16,Novatek,NOV,Industrie,Achat,166,68.70,12.85,Portefeuille A,11404.20,11417.05
921,2023-03-29,Novatek,NOV,Industrie,Achat,162,70.25,8.24,Portefeuille A,11380.50,11388.74
1223,2023-04-10,Novatek,NOV,Industrie,Achat,186,70.19,13.15,Portefeuille B,13055.34,13068.49

1. Calculez le `montant_brut` total échangé par secteur (`.groupby('secteur')['montant_brut'].sum()`), trié du plus élevé au moins élevé ;


2. Calculez, pour chaque secteur, le nombre d'opérations, le montant moyen et le montant total en une seule commande avec `.agg()`.

In [ ]:
print('Montant_brut Total echangé par Secteur')
display(transactions.groupby('secteur')['montant_brut'].sum())

transactions.groupby('secteur')['montant_brut'].agg(
    nbre_operation = 'count',
    montant_moyen = 'mean',
    montant_total = 'sum',
    montant_max = 'max',
    montant_min = 'min'
).sort_values(by = 'montant_total', ascending=False) #type :ignore

Montant_brut Total echangé par Secteur

secteur
Consommation    3.123778e+06
Finance         7.738912e+06
Immobilier      1.086015e+06
Industrie       4.921102e+06
Santé           3.924800e+06
Technologie     9.207538e+06
Transport       1.382929e+06
Énergie         3.172246e+06
Name: montant_brut, dtype: float64

,nbre_operation,montant_moyen,montant_total,montant_max,montant_min
secteur,,,,,
Technologie,607,15168.926154,9.207538e+06,57638.40,499.40
Finance,385,20101.068843,7.738912e+06,53383.00,682.25
Industrie,439,11209.799427,4.921102e+06,28152.06,325.10
Santé,395,9936.201656,3.924800e+06,23892.92,375.70
Énergie,394,8051.384805,3.172246e+06,29204.56,348.24
Consommation,384,8134.837258,3.123778e+06,21811.88,182.40
Transport,196,7055.758158,1.382929e+06,15535.38,238.80
Immobilier,200,5430.073608,1.086015e+06,11532.25,176.76